---
- name: "Install matplotlib"
  pip:
    name: "matplotlib"
    state: latest

- name: "Clone getnative"
  git:
    repo: "https://github.com/Infiziert90/getnative.git"
    dest: "/opt/getnative"
    version: "2.2.1"

- name: "Install getnative"
  script: "setup.py"
  args:
    chdir: "/opt/getnative"