---
- name: "Clone Vucan"
  git:
    repo: "https://github.com/nihui/waifu2x-ncnn-vulkan.git"
    dest: "/opt/vulcan"
    version: {{vulcan_version}}
    recursive: true

- name: "Create build dir"
  file:
    path: "/build/vulcan/build"
    state: directory
  args:
    chdir: "/opt/vulcan"

- name: "Build vulcan"
  shell: "{{item}}"
  with_items:
    - "cmake ../src"
    - "cmake --build . -j 4"
  args:
    chdir: "/opt/vulcan/build"

- name: "Install vulcan"
  shell: "cmake install"
  args:
    chdir: "/opt/vulcan/build"
