---
- name: "Clone Vucan"
  git:
    repo: "https://github.com/nihui/waifu2x-ncnn-vulkan.git"
    dest: "/opt/vulcan"
    version: "{{vulcan_version}}"
    recursive: true

- name: "Create build dir"
  file:
    path: "/opt/vulcan/build"
    state: directory

- name: "Build vulcan"
  shell: "{{item}}"
  with_items:
    - "cmake ../src"
    - "cmake --build . -j 4"
  args:
    chdir: "/opt/vulcan/build"
