---
- name: "Clone VapourSynth-Vulcan"
  git:
    repo: "https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan.git"
    dest: "/opt/vapour-vulcan"
    recursive: true
    version: "{{vapour_vulcan_version}}"

- name: "Create build dir"
  file:
    path: "/opt/vapour-vulcan/build"
    state: directory

- name: "Build VapourSynth-Vulcan"
  shell: "{{item}}"
  with_items:
    - "cmake .. -DVAPOURSYNTH_HEADER_DIR /usr/local/include/vapoursynth/"
    - "cmake --build . -j 4"
  args:
    chdir: "/opt/vapour-vulcan/build"
