---
- name: "Setup ffms2"
  hosts: "{{ target if target is defined else 'vapoursynth_servers'}}"
  remote_user: "{{ user | default('root') }}"
  become: true
  vars:
    ansible_port: "{{ ssh_port | default('22') }}"

  roles:
    - install_git
    - compile_ffms2