---
- name: "Create Script dir"
  file:
    path: "/opt/vapour-scripts/"
    state: directory
  tags:
    - setup-all
    - muvsfunc_numpy
    - edi_rpow2
    - bmtoolkit
    - alpha_cupy

- import_tasks: "{{ role_path }}/tasks/muvsfunc_numpy.yml"
  tags:
    - setup-all
    - muvsfunc_numpy

- import_tasks: "{{ role_path }}/tasks/edi_rpow2.yml"
  tags:
    - setup-all
    - edi_rpow2

- import_tasks: "{{ role_path }}/tasks/BMToolkit.yml"
  tags:
    - setup-all
    - bmtoolkit

- import_tasks: "{{ role_path }}/tasks/Alpha_CuPy.yml"
  tags:
    - setup-all
  when: cuda_enable

- import_tasks: "{{ role_path }}/tasks/Alpha_CuPy.yml"
  tags:
    - alpha_cupy
