---
- name: "Clone imagemagick"
  git:
    repo: "https://github.com/ImageMagick/ImageMagick.git"
    dest: "/opt/imagemagick"
    version: "7.0.11-6"

- name: "Autogeneration for imagemagick"
  shell: ./autogen.sh
  args:
    chdir: "/opt/imagemagick"

- name: "Configure imagemagick"
  shell: ./configure --enable-shared
  args:
    chdir: "/opt/imagemagick"

- name: "compile imagemagick"
  shell: make
  args:
    chdir: "/opt/imagemagick"

- name: "Install imagemagick"
  shell: make install
  args:
    chdir: "/opt/imagemagick"