---
- name: "Clone imagemagick"
  git:
    repo: "https://github.com/ImageMagick/ImageMagick.git"
    dest: "/opt/imagemagick"
    version: "{{imagemagick_version}}"

- name: "Configure imagemagick"
  shell: ./configure --enable-shared
  args:
    chdir: "/opt/imagemagick"

- name: "compile imagemagick"
  shell: "make -j{{compile_tasks}}"
  args:
    chdir: "/opt/imagemagick"

- name: "Install imagemagick"
  shell: make install
  args:
    chdir: "/opt/imagemagick"