---
- name: "Clone opencv"
  git:
    repo: "https://github.com/opencv/opencv.git"
    dest: "/opt/opencv"
    version: "{{ opencv_version }}"

- name: "Clone opencv-contrib"
  git:
    repo: "https://github.com/opencv/opencv_contrib.git"
    dest: "/opt/opencv-contrib"
    version: "{{ opencv_contrib_version }}"

- name: "Create build dir"
  file:
    path: "/opt/opencv/build"
    state: directory

- name: "Build for opencv"
  shell: "{{ item }}"
  with_items:
    - "cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D OPENCV_GENERATE_PKGCONFIG=ON -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv-contrib/modules -D BUILD_EXAMPLES=ON .."
    - "make -j4"
  args:
    chdir: "/opt/opencv/build"

- name: "Install opencv"
  shell: make install
  args:
    chdir: "/opt/opencv/build"