---
- name: "Clone Waifu2x"
  git:
    repo: "https://github.com/DeadSix27/waifu2x-converter-cpp.git"
    dest: "/opt/waifu2x"
    version: "{{ waifu2x_version | default('v5.3.4') }}"

- name: "Create out dir"
  file:
    path: "/opt/waifu2x/out"
    state: directory

- name: "Build Waifu2x"
  shell: "{{ item }}"
  with_items:
    - "cmake .."
    - "make -j4"
  args:
    chdir: "/opt/waifu2x/out"

- name: "Install Waifu2x"
  shell: "make install"
  args:
    chdir: "/opt/waifu2x/out"

- name: "Run ldconfig"
  shell: "ldconfig"
  args:
    chdir: "/opt/waifu2x/out"