---
- name: "Clone Vapoursynth-Waifu2x"
  git:
    repo: "https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc.git"
    dest: "/opt/vapour-waifu2x"
    version: "{{ vapour_waifu2x_version }}"

- name: "Build Vapoursynth-Waifu2x"
  shell: "{{ item }}"
  args:
    chdir: "/opt/vapour-waifu2x"
  with_items:
    - "meson build"
    - "ninja -C build"

- name: "Install Vapoursynth-Waifu2x"
  shell: "meson install -C build/"
  args:
    chdir: "/opt/vapour-waifu2x"