---
- name: "Clone VapourSynth"
  git:
    repo: https://github.com/vapoursynth/vapoursynth.git
    dest: "/opt/vapoursynth"
    version: "{{ vapoursynth_version }}"

- name: "Autogeneration for VapourSynth"
  shell: ./autogen.sh
  args:
    chdir: "/opt/vapoursynth"

- name: "Configure VapourSynth"
  shell: ./configure --enable-shared --enable-plugins
  args:
    chdir: "/opt/vapoursynth"

- name: "compile VapourSynth"
  shell: make -j4
  args:
    chdir: "/opt/vapoursynth"

- name: "Install VapourSynth"
  shell: make install
  args:
    chdir: "/opt/vapoursynth"

- name: "Set Environment Variables"
  shell: "echo '{{ item }}' >> /etc/environment"
  with_items:
    - "LD_LIBRARY_PATH=/usr/local/lib"
    - "PYTHONPATH=/usr/local/lib/{{ python_version | default('python3.8') }}/site-packages"