---
- name: "Clone zimg"
  git:
    repo: "https://github.com/sekrit-twc/zimg.git"
    dest: "/opt/zlib"
    version: "{{ zimg_version }}"

- name: "Autogeneration for zimg"
  shell: ./autogen.sh
  args:
    chdir: "/opt/zlib"

- name: "Configure zimg"
  shell: ./configure --enable-shared
  args:
    chdir: "/opt/zlib"

- name: "compile zimg"
  shell: make -j4
  args:
    chdir: "/opt/zlib"

- name: "Install zimg"
  shell: make install
  args:
    chdir: "/opt/zlib"